name: Vercel Production Deployment
on:
  push:
    branches:
      - main
jobs:
  CypressTest:
    runs-on: ubuntu-20.04
    name: Cypress Testing
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v4
        with:
          build: npm run build
          start: npm start
          browser: chrome
  BuildAndDeploy:
    needs: CypressTest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
